name: design_system
description: UI Design System for the enterprise mobile app
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Caching for images
  cached_network_image: ^3.2.2
  
  # Icons
  flutter_svg: ^2.0.10+1
  
  # Animations
  lottie: ^3.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
