name: core
description: Core business logic and utilities for the enterprise mobile app
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Network
  dio: ^5.7.0
  web_socket_channel: ^3.0.0
  grpc: ^3.2.4
    # Storage
  hive_flutter: ^1.1.0
  sqlite3_flutter_libs: ^0.5.0
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.3.2
  
  # Caching
  flutter_cache_manager: ^3.3.1
  
  # State Management & DI
  flutter_riverpod: ^2.3.4
  get_it: ^8.0.0
  injectable: ^2.5.0
  
  # Utilities
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  
  # Monitoring
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.0.0
  sentry_flutter: ^8.9.0
  
  # Logging
  logger: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.4
  
flutter:
